# autolisp-geometry --- matrices de transformation 4x4 pour AutoLISP

TEST_SUITE = autolisp-geometry

TEST_SOURCES = \
	-l ../autolisp-test/test-framework.lsp \
	-l src/autolisp-geometry.lsp \
	-l tests/geometry-tests.lsp \
	-l tests/run-tests.lsp

include ../makefiles/common.mk

.PHONY: clean

clean:
	@true
