#+TITLE: Manuel utilisateur
#+AUTHOR: OpenAI
#+LANGUAGE: fr
#+OPTIONS: toc:2 num:t

* Objet

Ce document décrit l'API publique de la bibliothèque =autolisp-misc=.

* Chargement

Pour charger le module de navigation façon shell (=pwd=, =cd=, =pushd=,
=popd=, =ls=, =cat=, =user-home-directory=, =home=) :

#+begin_src lisp
(load "src/browser.lsp")
#+end_src

Pour charger la fonction =cat= seule (sans les autres utilitaires) :

#+begin_src lisp
(load "src/cat.lsp")
#+end_src

Pour charger la fonction =format= :

#+begin_src lisp
(load "src/format.lsp")
#+end_src

Note : =src/fs.lsp= reste dans le dépôt mais ne fait plus partie du
projet. Il implémentait =pwd=, =cd= et =ls= avec un *cwd virtuel*
stocké dans =*misc-cwd*= ; =browser.lsp= le remplace en agissant sur
le *cwd réel* du processus.

* API publique

** =(cat arg)=

Affiche le contenu d'un ou plusieurs fichiers texte, dans le style de la
commande Unix =cat=.

L'argument =arg= peut être :

- une chaîne, pour afficher un seul fichier ;
- une liste de chaînes, pour afficher plusieurs fichiers dans l'ordre.

Exemples :

#+begin_src lisp
(cat "abc.txt")

(cat '("abc.txt" "def.txt"))

(cat '("abc.txt" "def.txt" "ghi.txt"))
#+end_src

Comportement :

- chaque fichier est ouvert en lecture puis affiché ligne par ligne ;
- si un fichier ne peut pas être ouvert, un message est affiché ;
- la fonction retourne silencieusement avec =(princ)=.

** Répertoire courant réel

Les fonctions =pwd=, =cd=, =pushd=, =popd= et =ls= (définies dans
=src/browser.lsp=) agissent sur le *répertoire courant réel* du
processus AutoCAD / BricsCAD, via l'objet COM =WScript.Shell=. Toute
fonction qui résout ses chemins via l'OS -- =(findfile ".")=,
=(open ...)=, =(load ...)=, =(vl-directory-files ".")= -- voit donc
les changements.

Le changement de cwd vaut pour la session CAO en cours. Au prochain
démarrage, le cwd revient à celui du raccourci AutoCAD / BricsCAD
(champ « Démarrer dans »).

L'objet COM =WScript.Shell= est mis en cache dans =*browser-shell*= ;
la pile partagée par =pushd= / =popd= est stockée dans
=*browser-stack*=.

** =(pwd)=

Affiche le chemin du répertoire courant réel et le renvoie sous forme
de chaîne.

#+begin_src lisp
(pwd)
#+end_src

** =(cd path)=

Change le répertoire courant réel. L'argument =path= est une chaîne
représentant un chemin absolu ou relatif au cwd courant.

- Si =path= désigne un répertoire existant, le cwd est mis à jour via
  =WScript.Shell.CurrentDirectory= et la fonction retourne la nouvelle
  valeur (telle que renvoyée par =CurrentDirectory= après affectation).
- Sinon un message d'erreur est affiché via =prompt= et =cd= retourne
  =nil=.

#+begin_src lisp
(cd "docs")
(cd "..")
(cd "C:/Users/Public")
#+end_src

** =(pushd path)=

Empile le cwd courant dans =*browser-stack*= puis change de répertoire
via =cd=. Retourne le nouveau cwd en cas de succès, =nil= sinon (auquel
cas la pile n'est pas modifiée).

#+begin_src lisp
(pushd "docs")
(pushd "..")
#+end_src

** =(popd)=

Dépile la première entrée de =*browser-stack*= et restaure ce
répertoire comme cwd courant. Retourne le cwd restauré, ou =nil= si la
pile est vide (avec un message via =prompt=).

#+begin_src lisp
(popd)
#+end_src

** =(ls flag)=

Liste le contenu du répertoire courant réel : fichiers *et*
sous-répertoires. Les répertoires sont signalés par un =/= final, à la
manière de =ls -F=.

- =(ls nil)= : listing court, un nom par ligne, trié.
- =(ls ':l)= ou =(ls ':long)= : listing détaillé avec, pour chaque
  entrée, le type (=d= pour un répertoire, =-= pour un fichier), la
  taille en octets, la date et heure de dernière modification, puis le
  nom (suffixé de =/= pour les répertoires).

Les entrées =.= et =..= sont omises. AutoLISP n'offre pas d'arguments
optionnels : l'appel =(ls)= sans argument est invalide ; utilisez
=(ls nil)= pour la forme courte.

#+begin_src lisp
(ls nil)
(ls ':l)
(ls ':long)
#+end_src

** =(truename path)= et =(path path)=

Résout un chemin contre le cwd réel :

- un chemin *absolu* est renvoyé tel quel ;
- un chemin *relatif* est préfixé par =(pwd)=.

Dans les deux cas le résultat est normalisé : les antislashs Windows
sont convertis en =/=, les segments =.= et =..= sont réduits.

=path= est un simple alias de =truename=.

Usage typique pour faire suivre =load= (ou tout autre opérateur qui
ne respecte pas le cwd, comme =findfile=) au répertoire courant :

#+begin_src lisp
(cd "C:/a/b/c/")
(load (path "foo.lsp"))   ;; charge C:/a/b/c/foo.lsp

(truename "/usr/local")   ;; => "/usr/local"
(truename "../sibling")   ;; relatif au pwd, normalisé
#+end_src

** =(user-home-directory)= et =(home)=

Renvoient le répertoire personnel de l'utilisateur sous forme de
chaîne, ou =nil= s'il n'est pas défini. =home= est un simple alias.

Source de la valeur :

- =USERPROFILE= (Windows) ;
- =HOME= en repli (Unix / macOS) ;
- =nil= si aucune des deux variables d'environnement n'est définie ou
  si elles sont vides.

#+begin_src lisp
(user-home-directory)
(home)
(cd (home))
#+end_src

** =(format control-string arguments)=

Construit et renvoie une chaîne en interprétant =control-string= selon
un sous-ensemble de la syntaxe de Common Lisp =format=.

L'argument =arguments= est une liste d'arguments consommés par les
directives du format.

Directives publiques prises en charge :

- =~A=, =~wA=, =~VA= : impression via =vl-princ-to-string=, alignée à
  gauche ;
- =~S=, =~wS=, =~VS= : impression via =vl-prin1-to-string=, alignée à
  gauche ;
- =~D=, =~B=, =~O=, =~X= avec largeur optionnelle ;
- pour =~A= et =~S=, le 4e paramètre peut fournir un caractère de
  remplissage, par exemple =~10,,,'-A= ;
- pour =~D=, =~B=, =~O= et =~X=, le 2e paramètre peut fournir un
  caractère de remplissage, par exemple =~10,'#X= ;
- =~F= et =~:F= avec largeur et précision optionnelles ;
- =~C= et =~@C= ;
- =~%=, =~&= et =~~=, avec répétition numérique ou via =V= ;
- =~{...~}=, =~:{...~}=, =~@{...~}= et =~:@{...~}= pour l'itération.

Exemples :

#+begin_src lisp
(format "~A = ~D" '("pommes" 12))
;; => "pommes = 12"

(format "~10,,,'-A" '("hello"))
;; => "hello-----"

(format "~10,'#X" '(42))
;; => "########2A"

(format "~{| ~10A | ~10D~%~}"
        '(("apple" 12 "orange" 423 "strawberry" 1200)))
#+end_src
